# name: Deploy Sphinx documentation to Pages

# on:
#   push:
#     branches: ["master"]   # or "main" depending on your branch
#   workflow_dispatch:

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.x"

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#           pip install sphinx sphinx-rtd-theme

#       - name: Build Sphinx documentation
#         run: |
#           # sphinx-build -b html source docs
# 		  sphinx-build source docs
#           touch docs/.nojekyll    # disable Jekyll

#       - name: Upload Pages artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: docs

#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4




name: "Publish sphinx documentation"

on: 
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser sphinx-tags sphinx-toolbox
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Sphinx build
        run: |
          sphinx-build source docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
